name: app
description: "Smart Inspection field tracking app."
publish_to: 'none'

version: 1.0.2+3

environment:
  sdk: ^3.6.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_secure_storage: ^10.3.1
  http: ^1.6.0
  uuid: ^4.6.0
  permission_handler: ^13.0.0
  flutter_foreground_task: ^9.2.2
  workmanager: 0.7.0
  geolocator: ^14.0.2
  sqflite: ^2.4.1
  path: ^1.9.0
  battery_plus: ^7.1.1
  package_info_plus: ^9.0.1
  open_filex: ^4.7.0
  path_provider: ^2.1.5
  flutter_local_notifications: ^19.5.0
  image_picker: ^1.1.2
  web_socket_channel: ^3.0.1
  flutter_map: ^8.3.1
  latlong2: ^0.10.1
  mime: ^2.0.0
  http_parser: ^4.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

dependency_overrides:
  permission_handler_android: 13.0.1
  geolocator_android: 4.6.2
  image_picker_android: 0.8.12+22

flutter:
  uses-material-design: true

  assets:
    - assets/brand/
