#!/usr/bin/env bash
set -euo pipefail

REPO="$(cd "$(dirname "$0")/.." && pwd)"

read_env() {
    local file="$1" key="$2" fallback="${3:-}"
    local value
    value="$(grep -E "^${key}=" "$file" 2>/dev/null | tail -1 | cut -d= -f2- | sed 's/^"//; s/"$//')" || true
    echo "${value:-$fallback}"
}

ROOT_ENV="$REPO/.env"
API_ENV="$REPO/api/.env"

LAN_HOST="$(read_env "$ROOT_ENV" LAN_HOST localhost)"
API_PORT="$(read_env "$ROOT_ENV" API_PORT 8000)"
REVERB_PORT="$(read_env "$ROOT_ENV" REVERB_PORT 8080)"
PANEL_PORT="$(read_env "$ROOT_ENV" PANEL_PORT 3000)"
PG_PORT="$(read_env "$ROOT_ENV" POSTGRES_PORT 5432)"
REDIS_PORT="$(read_env "$ROOT_ENV" REDIS_PORT 6379)"
PG_DB="$(read_env "$ROOT_ENV" POSTGRES_DB api)"
PG_USER="$(read_env "$ROOT_ENV" POSTGRES_USER api)"
PG_PASS="$(read_env "$ROOT_ENV" POSTGRES_PASSWORD secret)"

ADMIN_EMAIL="$(read_env "$API_ENV" SEED_ADMIN_EMAIL test@example.com)"
ADMIN_PASS="$(read_env "$API_ENV" SEED_ADMIN_PASSWORD password)"
APP_DEBUG="$(read_env "$API_ENV" APP_DEBUG false)"

STAFF_PASS="$(grep -oE "DEFAULT_PASSWORD = '[^']*'" "$REPO/api/database/seeders/StaffSeeder.php" | cut -d"'" -f2)"
STAFF_PASS="${STAFF_PASS:-password}"

MIN_SDK="$(grep -oE 'minSdk = [0-9]+' "$REPO/app/android/app/build.gradle" | grep -oE '[0-9]+')"

cat > "$REPO/information.txt" <<EOF
================================================================
 SMART INSPECTION - LOCAL ACCESS INFORMATION
 Generated by scripts/write-information.sh on $(date +%Y-%m-%d).
 Do not edit by hand: re-run the script instead, so these values
 can never drift from the real configuration again.
 Git-ignored. Never commit this file.
================================================================

----------------------------------------------------------------
 ADDRESSES
----------------------------------------------------------------
On this machine
  Admin panel                      http://localhost:${PANEL_PORT}
  API                              http://localhost:${API_PORT}
  API health check                 http://localhost:${API_PORT}/up
  WebSocket (Laravel Reverb)       ws://localhost:${REVERB_PORT}

From another device on the same Wi-Fi
  Admin panel                      http://${LAN_HOST}:${PANEL_PORT}
  API                              http://${LAN_HOST}:${API_PORT}

From the Android emulator
  API                              http://10.0.2.2:${API_PORT}

Databases (not reachable from the network, by design)
  Postgres + PostGIS               127.0.0.1:${PG_PORT}
  Redis                            127.0.0.1:${REDIS_PORT}

${LAN_HOST} is set once, as LAN_HOST in the root .env. It feeds the
API's CORS and Sanctum allow-lists and the URL baked into the APK.
If it changes: edit .env, run docker compose up -d, rebuild the
APK, and re-run this script.

The panel needs no rebuild when the address changes. It derives
the API origin from whatever host the browser loaded it from.

Host ports are all below 49152 on purpose. Windows reserves
several ranges between 50000 and 60000 for Hyper-V/WSL2, which is
what previously stopped the api container from starting. List them
with:
  netsh.exe interface ipv4 show excludedportrange protocol=tcp

----------------------------------------------------------------
 PANEL LOGINS  (email + password)
----------------------------------------------------------------
Role         Email                          Password
admin        ${ADMIN_EMAIL}$(printf '%*s' $((31 - ${#ADMIN_EMAIL})) '')${ADMIN_PASS}
hr           hr@example.com                 ${STAFF_PASS}
supervisor   supervisor@example.com         ${STAFF_PASS}
supervisor   supervisor2@example.com        ${STAFF_PASS}

The admin account comes from SEED_ADMIN_EMAIL / SEED_ADMIN_PASSWORD
in api/.env. Change those, re-seed, and re-run this script.

Capabilities:
  admin       manage-schedules + view-locations
  hr          manage-schedules
  supervisor  view-locations

----------------------------------------------------------------
 MOBILE APP LOGINS  (username + password)
----------------------------------------------------------------
Employees authenticate with username, not email.

Username   Name                 Status
ahmed      Ahmed Al Saadi       active, NO device paired
fatma      Fatma Al Kindi       active, NO device paired
yusuf      Yusuf Al Harthy      active   (Default shift, leave in 3 days)
noura      Noura Al Amri        active   (overtime today)
khalid     Khalid Al Rawahi     active   (Default shift, half-day leave tomorrow)
aisha      Aisha Al Zadjali     active   (Ramadan shift)
omar       Omar Al Maskari      active   (early end today)
layla      Layla Al Habsi       INACTIVE (login is refused)

Password for every employee: ${STAFF_PASS}

Only one active device per employee is allowed. To move an employee
to a new phone, revoke the device from the panel first.

The seeders deliberately leave ahmed and fatma without a paired
device, so you can always sign in on a fresh phone or emulator.
Every other employee already has a seeded device and will be
refused until you revoke it.

----------------------------------------------------------------
 THE APK
----------------------------------------------------------------
File            dist/smart-inspection.apk   (~50 MB)
Package         com.smartinspection.tracking
Minimum         Android $(case "$MIN_SDK" in 21) echo "5.0";; 23) echo "6.0";; 24) echo "7.0";; 26) echo "8.0";; *) echo "API $MIN_SDK";; esac) (API ${MIN_SDK})
Target          Android 16 (API 36)
ABIs            arm64-v8a, armeabi-v7a, x86_64
Signing         release key, APK Signature Scheme v2
Points at       http://${LAN_HOST}:${API_PORT}

One APK for every phone: all three ABIs are in it, so it installs
on 32-bit and 64-bit ARM devices and on x86_64 emulators alike.

API ${MIN_SDK} is the real floor, not a preference. shared_preferences
(pulled in transitively) requires 24 and flutter_secure_storage
requires 23. Nothing in the app itself needs above 21.

To install: copy the APK to the phone and open it. Android will ask
you to allow installing from unknown sources, because this is not
distributed through Play.

Cleartext HTTP is allowed only for localhost, 10.0.2.2 and
${LAN_HOST}, and refused everywhere else, so the app cannot be
tricked into sending data unencrypted to an arbitrary host. Put a
TLS terminator in front of the API before this leaves a trusted
network.

Signing keys live in app/android/key.properties and
app/android/smartinspection-release.jks. Both are git-ignored.
Back them up: losing them means no future build can upgrade an
already-installed app.

----------------------------------------------------------------
 ANDROID EMULATOR
----------------------------------------------------------------
The Windows-side toolchain lives outside the repo:

JDK 17            E:\\Android\\jdk-17.0.20+8
Android SDK       E:\\Android\\sdk
AVD home          E:\\Android\\avd
AVD name          inspection_pixel   (Pixel 6, API 35, x86_64)
Flutter           E:\\flutter

Boot the emulator:
  E:\\Android\\sdk\\emulator\\emulator.exe -avd inspection_pixel

Gradle cannot build over the \\\\wsl.localhost UNC path: its file
hasher fails with "java.io.IOException: Incorrect function".
scripts/build-apk.sh handles this by syncing app/ to E:\\inspection-app
and building there. Analyzer and unit tests run fine directly on the
WSL path; only the Gradle/APK step needs the copy.

----------------------------------------------------------------
 DATABASE
----------------------------------------------------------------
Host      127.0.0.1
Port      ${PG_PORT}
Database  ${PG_DB}
User      ${PG_USER}
Password  ${PG_PASS}

psql:
  docker compose exec postgres psql -U ${PG_USER} -d ${PG_DB}

Tests use a separate database, ${PG_DB}_testing, and must never touch
${PG_DB}. Verify after changing anything about the environment:
seed, run the suite, then confirm ${PG_DB} still has rows.

----------------------------------------------------------------
 COMMON COMMANDS
----------------------------------------------------------------
docker compose up -d                 (api, panel, postgres, redis)
docker compose logs -f api
docker compose logs -f panel
docker compose exec api php artisan migrate:fresh --seed
docker compose exec api php artisan test

./scripts/build-apk.sh               (uses LAN_HOST from .env)
./scripts/build-apk.sh 192.168.1.50  (or pass an address)
./scripts/write-information.sh       (regenerate this file)

----------------------------------------------------------------
 SECURITY NOTES
----------------------------------------------------------------
1. APP_DEBUG is currently ${APP_DEBUG}. It must stay false while the
   API is reachable from the network: a stack trace is a map of the
   application.
2. Every credential above is a local development default. None may
   be used in production. The seeders that create them refuse to run
   when APP_ENV=production.
3. .env and api/.env were previously committed to git. They are now
   untracked and ignored, but the old APP_KEY and database password
   still exist in the git history. Rotate both before this repository
   is pushed anywhere shared:
     docker compose exec api php artisan key:generate
4. Deactivating an employee or resetting their password deletes their
   API tokens, so an issued mobile token cannot outlive the change.
5. Postgres and Redis are published on 127.0.0.1 only. Only the API,
   Reverb and the panel are reachable from the network.
EOF

echo "Wrote $REPO/information.txt"
